version: '2'
services:
    registry:
        restart: always
        image: registry:2.7.0
        ports:
          - 5000:5000
        environment:
          REGISTRY_AUTH: htpasswd
          REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
          REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
        volumes:
          - /media/usb/registry:/var/lib/registry          
          - /media/app/docker-registry/auth:/auth

# 레지스트리 BasicAuth 만들기           
# mkdir auth
# docker run --entrypoint htpasswd registry:2.7.0 -Bbn 사용자ID 사용자PW > auth/htpasswd